services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Novactive\Bundle\eZExtraBundle\Command\CreateContentTypesCommand:
        bind:
            $translationHelper: '@ezpublish.translation_helper'

    Novactive\Bundle\eZExtraBundle\Core\Helper\eZ\WrapperFactory: ~
    Novactive\Bundle\eZExtraBundle\Core\Manager\eZ\Content: ~
    Novactive\Bundle\eZExtraBundle\Core\Manager\eZ\ContentType: ~
    Novactive\Bundle\eZExtraBundle\Core\Helper\eZ\Content: ~

    novactive.ezextra.twig.extension.content:
        class: Novactive\Bundle\eZExtraBundle\Twig\ContentExtension
        parent: ezpublish.twig.extension.content
        tags:
            - {name: twig.extension}

    Novactive\Bundle\eZExtraBundle\EventListener\PreContentViewListener:
        arguments: ['@ezpublish.api.repository', '@ezpublish.templating.global_helper']
        tags:
            - {name: kernel.event_listener, event: ezpublish.pre_content_view, method: onPreContentView}

