parameters:
    env(ENABLE_IMAGE_PLACEHOLDER): true
#    env(IMAGE_TAG_TEMPLATE_PATH): '@NovaeZExtra/fields/display_image_tag.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Novactive\Bundle\eZExtraBundle\Command\CreateContentTypesCommand:
        bind:
            $translationHelper: '@ezpublish.translation_helper'

    Novactive\Bundle\eZExtraBundle\Core\Helper\eZ\WrapperFactory: ~
    Novactive\Bundle\eZExtraBundle\Core\Manager\eZ\Content: ~
    Novactive\Bundle\eZExtraBundle\Core\Manager\eZ\ContentType: ~
    Novactive\Bundle\eZExtraBundle\Core\Helper\eZ\Content: ~

    Novactive\Bundle\eZExtraBundle\Twig\ContentExtension: ~
    Novactive\Bundle\eZExtraBundle\Twig\TextParsingExtension: ~
    Novactive\Bundle\eZExtraBundle\Twig\ImageExtension:
        bind:
            $enableImagePlaceholder: '%env(bool:ENABLE_IMAGE_PLACEHOLDER)%'

    Novactive\Bundle\eZExtraBundle\EventListener\PreContentViewListener:
        arguments: ['@ezpublish.api.repository', '@ezpublish.templating.global_helper']
        tags:
            - {name: kernel.event_listener, event: ezpublish.pre_content_view, method: onPreContentView}

